name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build and publish API Core to mavenLocal
        run: ./gradlew publishToMavenLocal
      - name: clean gradle cache before TDBR build
        run: rm -rf ~/.gradle/caches/
      - name: build TDBR module (standalone)
        run: |
          cd nexus-tdbr-standalone
          ../gradlew build --no-daemon
      - name: capture build artifacts (Nexus API Core)
        uses: actions/upload-artifact@v7
        with:
          name: nexus-api-core
          path: build/libs/
      - name: capture build artifacts (TDBR module)
        uses: actions/upload-artifact@v7
        with:
          name: nexus-tdbr
          path: nexus-tdbr-standalone/build/libs/
